version: '2'
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    ports:
      - "3003:3003"
    restart: always
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    ports:
      - "8000:80"
    restart: always